import pdfMake from 'pdfmake/build/pdfmake';
import * as pdfFonts from 'pdfmake/build/vfs_fonts';

if (pdfFonts && pdfFonts.pdfMake && pdfFonts.pdfMake.vfs) {
  pdfMake.vfs = pdfFonts.pdfMake.vfs;
} else if (pdfFonts && pdfFonts.vfs) {
  pdfMake.vfs = pdfFonts.vfs;
} else {
  pdfMake.vfs = window.pdfMake?.vfs || {};
}

const formatCurrency = (value = 0) => `₹${Number(value || 0).toLocaleString('en-IN')}`;
const formatDate = (dateValue) => {
  if (!dateValue) return 'N/A';
  const date = new Date(dateValue);
  return date.toLocaleDateString('en-IN', { day: '2-digit', month: '2-digit', year: 'numeric' });
};

const formatTime = (dateValue) => {
  if (!dateValue) return 'N/A';
  const date = new Date(dateValue);
  return date.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
};

const buildHeader = (reportData, adminName) => ({
  columns: [
    [
      { text: 'Finance Collection System', style: 'reportTitle' },
      { text: `Generated by ${adminName}`, style: 'reportMeta' }
    ],
    [
      { text: `Report Date: ${formatDate(reportData.reportDate)}`, alignment: 'right', style: 'reportMeta' },
      { text: `Generated Time: ${formatTime(reportData.reportTime)}`, alignment: 'right', style: 'reportMeta' }
    ]
  ],
  columnGap: 10,
  margin: [0, 0, 0, 16]
});

const buildSummarySection = (summary) => ({
  columns: [
    {
      width: '20%',
      stack: [
        { text: 'Customers Due Today', style: 'summaryLabel' },
        { text: `${summary.totalCustomersDueToday}`, style: 'summaryValue' }
      ]
    },
    {
      width: '20%',
      stack: [
        { text: 'Due Amount Today', style: 'summaryLabel' },
        { text: formatCurrency(summary.totalDueAmountToday), style: 'summaryValue' }
      ]
    },
    {
      width: '20%',
      stack: [
        { text: 'Collected Today', style: 'summaryLabel' },
        { text: formatCurrency(summary.totalCollectedAmountToday), style: 'summaryValue' }
      ]
    },
    {
      width: '20%',
      stack: [
        { text: 'Remaining Balance', style: 'summaryLabel' },
        { text: formatCurrency(summary.remainingBalanceToday), style: 'summaryValue' }
      ]
    },
    {
      width: '20%',
      stack: [
        { text: 'Overdue Customers', style: 'summaryLabel' },
        { text: `${summary.overdueCustomersCount}`, style: 'summaryValue' }
      ]
    }
  ],
  columnGap: 8,
  margin: [0, 0, 0, 16]
});

const buildTable = (header, rows, columns) => ({
  text: header,
  style: 'sectionHeader',
  margin: [0, 12, 0, 6],
  tocItem: false,
  table: {
    widths: columns.map((column) => column.width),
    body: [
      columns.map((column) => ({ text: column.title, style: 'tableHeader' })),
      ...rows
    ]
  },
  layout: {
    fillColor: (rowIndex) => (rowIndex === 0 ? '#F3F4F6' : null),
    hLineWidth: () => 0.5,
    vLineWidth: () => 0.5,
    hLineColor: () => '#D1D5DB',
    vLineColor: () => '#D1D5DB'
  }
});

const buildPaidCustomersRows = (paidCustomers) => {
  if (!paidCustomers.length) {
    return [[{ text: 'No payments recorded today', colSpan: 4, alignment: 'center', margin: [0, 8, 0, 8] }, {}, {}, {}]];
  }

  return paidCustomers.map((payment) => ([
    { text: payment.customerName || 'Unknown', margin: [0, 4, 0, 4] },
    { text: formatCurrency(payment.amountPaid), margin: [0, 4, 0, 4] },
    { text: formatTime(payment.paymentTime), margin: [0, 4, 0, 4] },
    { text: payment.status || 'Paid', margin: [0, 4, 0, 4] }
  ]));
};

const buildPendingCustomersRows = (pendingCustomers) => {
  if (!pendingCustomers.length) {
    return [[{ text: 'No pending customers for today', colSpan: 4, alignment: 'center', margin: [0, 8, 0, 8] }, {}, {}, {}]];
  }

  return pendingCustomers.map((payment) => ([
    { text: payment.customerName || 'Unknown', margin: [0, 4, 0, 4] },
    { text: formatCurrency(payment.dueAmount), margin: [0, 4, 0, 4] },
    { text: formatCurrency(payment.pendingBalance), margin: [0, 4, 0, 4] },
    { text: formatDate(payment.dueDate), margin: [0, 4, 0, 4] }
  ]));
};

const buildOverdueCustomersRows = (overdueCustomers) => {
  if (!overdueCustomers.length) {
    return [[{ text: 'No overdue customers', colSpan: 3, alignment: 'center', margin: [0, 8, 0, 8] }, {}, {}]];
  }

  return overdueCustomers.map((payment) => ([
    { text: payment.customerName || 'Unknown', margin: [0, 4, 0, 4] },
    { text: `${payment.overdueDays} day${payment.overdueDays === 1 ? '' : 's'}`, margin: [0, 4, 0, 4] },
    { text: formatCurrency(payment.pendingAmount), margin: [0, 4, 0, 4] }
  ]));
};

const buildActivitySection = (dailyActivity = []) => {
  if (!dailyActivity.length) {
    return { text: 'No finance activity recorded for today', margin: [0, 8, 0, 8] };
  }

  return {
    stack: [
      { text: 'Daily Finance Activity', style: 'sectionHeader', margin: [0, 12, 0, 6] },
      {
        columns: dailyActivity.map((entry) => ({
          width: 'auto',
          stack: [
            { text: entry.label, style: 'activityLabel' },
            { text: /Amount|Balance/i.test(entry.label) ? formatCurrency(entry.value) : String(entry.value), style: 'activityValue' }
          ]
        })),
        columnGap: 10
      }
    ]
  };
};

const buildFooter = (summary) => ({
  columns: [
    { text: `Total Collected: ${formatCurrency(summary.totalCollectedAmountToday)}`, style: 'footerText' },
    { text: `Remaining Balance: ${formatCurrency(summary.remainingBalanceToday)}`, style: 'footerText', alignment: 'right' }
  ],
  margin: [0, 20, 0, 0]
});

const buildDocumentDefinition = (reportData, adminName) => {
  return {
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 40],
    defaultStyle: {
      fontSize: 10,
      columnGap: 15
    },
    content: [
      buildHeader(reportData, adminName),
      { text: 'Daily Collection Report', style: 'title', margin: [0, 0, 0, 8] },
      { text: `Financial summary for ${reportData.dayOfWeek}`, style: 'subTitle', margin: [0, 0, 0, 12] },
      buildSummarySection(reportData.summary),
      buildActivitySection(reportData.dailyActivity),
      buildTable('Paid Customers', buildPaidCustomersRows(reportData.paidCustomers), [
        { title: 'Customer', width: '35%' },
        { title: 'Amount Paid', width: '20%' },
        { title: 'Payment Time', width: '25%' },
        { title: 'Status', width: '20%' }
      ]),
      buildTable('Pending Customers', buildPendingCustomersRows(reportData.pendingCustomers), [
        { title: 'Customer', width: '30%' },
        { title: 'Due Amount', width: '20%' },
        { title: 'Pending Balance', width: '25%' },
        { title: 'Due Date', width: '25%' }
      ]),
      buildTable('Overdue Customers', buildOverdueCustomersRows(reportData.overdueCustomers), [
        { title: 'Customer', width: '45%' },
        { title: 'Overdue Days', width: '25%' },
        { title: 'Pending Amount', width: '30%' }
      ]),
      buildFooter(reportData.summary),
      { text: 'Generated automatically by system', style: 'note', margin: [0, 8, 0, 0] }
    ],
    styles: {
      reportTitle: { fontSize: 16, bold: true, color: '#111827' },
      reportMeta: { fontSize: 9, color: '#4B5563' },
      title: { fontSize: 14, bold: true, color: '#111827' },
      subTitle: { fontSize: 10, color: '#6B7280' },
      summaryLabel: { fontSize: 8, color: '#6B7280', margin: [0, 0, 0, 4], bold: true },
      summaryValue: { fontSize: 12, bold: true, color: '#111827' },
      sectionHeader: { fontSize: 12, bold: true, margin: [0, 12, 0, 6], color: '#111827' },
      activityLabel: { fontSize: 8, color: '#6B7280', margin: [0, 0, 0, 2], bold: true },
      activityValue: { fontSize: 11, bold: true, color: '#111827' },
      tableHeader: { bold: true, color: '#111827', fontSize: 10 },
      footerText: { fontSize: 9, bold: true, color: '#111827' },
      note: { fontSize: 9, italics: true, color: '#6B7280' }
    }
  };
};

export const downloadDailyReport = (reportData, adminName, fileName) => {
  const documentDefinition = buildDocumentDefinition(reportData, adminName);
  pdfMake.createPdf(documentDefinition).download(fileName);
};

export const printDailyReport = (reportData, adminName) => {
  const documentDefinition = buildDocumentDefinition(reportData, adminName);
  pdfMake.createPdf(documentDefinition).print();
};

const createReportBlob = (reportData, adminName) => new Promise((resolve, reject) => {
  const documentDefinition = buildDocumentDefinition(reportData, adminName);
  pdfMake.createPdf(documentDefinition).getBlob((blob) => {
    if (!blob) {
      reject(new Error('Failed to create report PDF'));
      return;
    }
    resolve(blob);
  });
});

export const shareDailyReport = async (reportData, adminName, fileName) => {
  const blob = await createReportBlob(reportData, adminName);
  const file = new File([blob], fileName, { type: 'application/pdf' });

  if (navigator.share) {
    const shareData = {
      title: 'Daily Collection Report',
      text: 'Please find the daily finance collection report attached.',
      files: [file]
    };

    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share(shareData);
      return;
    }

    await navigator.share({
      title: 'Daily Collection Report',
      text: 'Daily finance collection report has been generated and downloaded to your device. Please attach it in WhatsApp.'
    });
    return;
  }

  const message = 'Daily finance collection report generated. Please attach the downloaded PDF from your device and share it on WhatsApp.';
  window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
};
